FROM php:7.2.5-apache

# Update the image
RUN apt update -y && apt upgrade -y && apt install -y git libicu-dev libpq-dev wget zlib1g-dev

# PHP Extensions
RUN docker-php-ext-install intl opcache pdo_pgsql pgsql zip
RUN pecl install xdebug && docker-php-ext-enable xdebug
RUN echo "\
[xdebug]\n\
xdebug.mode = develop,debug\n\
xdebug.start_with_request = yes\n\
xdebug.client_host = host.docker.internal\n\
xdebug.client_port = 9003\n\
" > /usr/local/etc/php/conf.d/xdebug.ini

# PHP Config
RUN echo "short_open_tag = Off" > /usr/local/etc/php/php.ini

# Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer

# Symfony CLI
RUN wget https://github.com/symfony-cli/symfony-cli/releases/download/v5.4.7/symfony-cli_linux_amd64.tar.gz \
    && tar -xvzf symfony-cli_linux_amd64.tar.gz \
    && rm README.md LICENSE \
    && mv symfony /usr/local/bin/symfony

# Configure Apache
RUN sed -i -e "s/DocumentRoot \/var\/www\/html/DocumentRoot \/var\/www\/html\/public/g" /etc/apache2/sites-available/000-default.conf
RUN a2enmod rewrite

# Remove not needed packages
RUN apt autoremove --purge -y git wget

EXPOSE 80